[package]
name = "cs425-mp2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4"
rand = "0.8"
